/*
 * This file is generated by jOOQ.
 */
package cn.zenliu.jcef.model.tables;


import cn.zenliu.jcef.model.Indexes;
import cn.zenliu.jcef.model.Keys;
import cn.zenliu.jcef.model.Public;
import cn.zenliu.jcef.model.tables.records.ConferenceRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Conference extends TableImpl<ConferenceRecord> {

    private static final long serialVersionUID = 694663238;

    /**
     * The reference instance of <code>public.conference</code>
     */
    public static final Conference CONFERENCE = new Conference();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConferenceRecord> getRecordType() {
        return ConferenceRecord.class;
    }

    /**
     * The column <code>public.conference.idx</code>.
     */
    public final TableField<ConferenceRecord, Integer> IDX = createField("idx", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.conference.create_at</code>.
     */
    public final TableField<ConferenceRecord, LocalDateTime> CREATE_AT = createField("create_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.conference.name</code>.
     */
    public final TableField<ConferenceRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.conference.net_id</code>.
     */
    public final TableField<ConferenceRecord, String> NET_ID = createField("net_id", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>public.conference</code> table reference
     */
    public Conference() {
        this(DSL.name("conference"), null);
    }

    /**
     * Create an aliased <code>public.conference</code> table reference
     */
    public Conference(String alias) {
        this(DSL.name(alias), CONFERENCE);
    }

    /**
     * Create an aliased <code>public.conference</code> table reference
     */
    public Conference(Name alias) {
        this(alias, CONFERENCE);
    }

    private Conference(Name alias, Table<ConferenceRecord> aliased) {
        this(alias, aliased, null);
    }

    private Conference(Name alias, Table<ConferenceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Conference(Table<O> child, ForeignKey<O, ConferenceRecord> key) {
        super(child, key, CONFERENCE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONFERENCE__INDEX_NAME, Indexes.PRIMARY_KEY_4);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ConferenceRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CONFERENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ConferenceRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ConferenceRecord>> getKeys() {
        return Arrays.<UniqueKey<ConferenceRecord>>asList(Keys.CONSTRAINT_4);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Conference as(String alias) {
        return new Conference(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Conference as(Name alias) {
        return new Conference(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Conference rename(String name) {
        return new Conference(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Conference rename(Name name) {
        return new Conference(name, null);
    }
}
