/*
 * This file is generated by jOOQ.
 */
package cn.zenliu.jcef.model;


import cn.zenliu.jcef.model.tables.Conference;
import cn.zenliu.jcef.model.tables.Sign;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONFERENCE__INDEX_NAME = Indexes0.CONFERENCE__INDEX_NAME;
    public static final Index PRIMARY_KEY_4 = Indexes0.PRIMARY_KEY_4;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONFERENCE__INDEX_NAME = Internal.createIndex("conference__index_name", Conference.CONFERENCE, new OrderField[] { Conference.CONFERENCE.NAME }, true);
        public static Index PRIMARY_KEY_4 = Internal.createIndex("primary_key_4", Conference.CONFERENCE, new OrderField[] { Conference.CONFERENCE.IDX }, true);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("primary_key_2", Sign.SIGN, new OrderField[] { Sign.SIGN.IDX }, true);
    }
}
