/*
 * This file is generated by jOOQ.
 */
package cn.zenliu.jcef.model;


import cn.zenliu.jcef.model.tables.Conference;
import cn.zenliu.jcef.model.tables.Sign;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 902520059;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.conference</code>.
     */
    public final Conference CONFERENCE = cn.zenliu.jcef.model.tables.Conference.CONFERENCE;

    /**
     * The table <code>public.sign</code>.
     */
    public final Sign SIGN = cn.zenliu.jcef.model.tables.Sign.SIGN;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Conference.CONFERENCE,
            Sign.SIGN);
    }
}
