/*
 * This file is generated by jOOQ.
 */
package cn.zenliu.jcef.model.tables.records;


import cn.zenliu.jcef.model.tables.Sign;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SignRecord extends UpdatableRecordImpl<SignRecord> implements Record9<Integer, String, Integer, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -455771291;

    /**
     * Setter for <code>public.sign.idx</code>.
     */
    public SignRecord setIdx(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.sign.idx</code>.
     */
    public Integer getIdx() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.sign.name</code>.
     */
    public SignRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.sign.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.sign.conf_id</code>.
     */
    public SignRecord setConfId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.sign.conf_id</code>.
     */
    public Integer getConfId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.sign.depart</code>.
     */
    public SignRecord setDepart(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.sign.depart</code>.
     */
    public String getDepart() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.sign.device_id</code>.
     */
    public SignRecord setDeviceId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.sign.device_id</code>.
     */
    public String getDeviceId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.sign.card_id</code>.
     */
    public SignRecord setCardId(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.sign.card_id</code>.
     */
    public String getCardId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.sign.card_type</code>.
     */
    public SignRecord setCardType(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.sign.card_type</code>.
     */
    public String getCardType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.sign.check_in</code>.
     */
    public SignRecord setCheckIn(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.sign.check_in</code>.
     */
    public LocalDateTime getCheckIn() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.sign.check_out</code>.
     */
    public SignRecord setCheckOut(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.sign.check_out</code>.
     */
    public LocalDateTime getCheckOut() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Sign.SIGN.IDX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Sign.SIGN.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Sign.SIGN.CONF_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Sign.SIGN.DEPART;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Sign.SIGN.DEVICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Sign.SIGN.CARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Sign.SIGN.CARD_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return Sign.SIGN.CHECK_IN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return Sign.SIGN.CHECK_OUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getConfId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDepart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDeviceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCardType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getCheckIn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component9() {
        return getCheckOut();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getConfId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDepart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDeviceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCardType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getCheckIn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getCheckOut();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SignRecord value1(Integer value) {
        setIdx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SignRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SignRecord value3(Integer value) {
        setConfId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SignRecord value4(String value) {
        setDepart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SignRecord value5(String value) {
        setDeviceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SignRecord value6(String value) {
        setCardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SignRecord value7(String value) {
        setCardType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SignRecord value8(LocalDateTime value) {
        setCheckIn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SignRecord value9(LocalDateTime value) {
        setCheckOut(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SignRecord values(Integer value1, String value2, Integer value3, String value4, String value5, String value6, String value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SignRecord
     */
    public SignRecord() {
        super(Sign.SIGN);
    }

    /**
     * Create a detached, initialised SignRecord
     */
    public SignRecord(Integer idx, String name, Integer confId, String depart, String deviceId, String cardId, String cardType, LocalDateTime checkIn, LocalDateTime checkOut) {
        super(Sign.SIGN);

        set(0, idx);
        set(1, name);
        set(2, confId);
        set(3, depart);
        set(4, deviceId);
        set(5, cardId);
        set(6, cardType);
        set(7, checkIn);
        set(8, checkOut);
    }
}
