/*
 * This file is generated by jOOQ.
 */
package cn.zenliu.jcef.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Conference implements Serializable {

    private static final long serialVersionUID = -1724277562;

    private Integer       idx;
    private LocalDateTime createAt;
    private String        name;
    private String        netId;

    public Conference() {}

    public Conference(Conference value) {
        this.idx = value.idx;
        this.createAt = value.createAt;
        this.name = value.name;
        this.netId = value.netId;
    }

    public Conference(
        Integer       idx,
        LocalDateTime createAt,
        String        name,
        String        netId
    ) {
        this.idx = idx;
        this.createAt = createAt;
        this.name = name;
        this.netId = netId;
    }

    public Integer getIdx() {
        return this.idx;
    }

    public Conference setIdx(Integer idx) {
        this.idx = idx;
        return this;
    }

    public LocalDateTime getCreateAt() {
        return this.createAt;
    }

    public Conference setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Conference setName(String name) {
        this.name = name;
        return this;
    }

    public String getNetId() {
        return this.netId;
    }

    public Conference setNetId(String netId) {
        this.netId = netId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Conference (");

        sb.append(idx);
        sb.append(", ").append(createAt);
        sb.append(", ").append(name);
        sb.append(", ").append(netId);

        sb.append(")");
        return sb.toString();
    }
}
