/*
 * This file is generated by jOOQ.
 */
package cn.zenliu.jcef.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sign implements Serializable {

    private static final long serialVersionUID = 88365701;

    private Integer       idx;
    private String        name;
    private Integer       confId;
    private String        depart;
    private String        deviceId;
    private String        cardId;
    private String        cardType;
    private LocalDateTime checkIn;
    private LocalDateTime checkOut;

    public Sign() {}

    public Sign(Sign value) {
        this.idx = value.idx;
        this.name = value.name;
        this.confId = value.confId;
        this.depart = value.depart;
        this.deviceId = value.deviceId;
        this.cardId = value.cardId;
        this.cardType = value.cardType;
        this.checkIn = value.checkIn;
        this.checkOut = value.checkOut;
    }

    public Sign(
        Integer       idx,
        String        name,
        Integer       confId,
        String        depart,
        String        deviceId,
        String        cardId,
        String        cardType,
        LocalDateTime checkIn,
        LocalDateTime checkOut
    ) {
        this.idx = idx;
        this.name = name;
        this.confId = confId;
        this.depart = depart;
        this.deviceId = deviceId;
        this.cardId = cardId;
        this.cardType = cardType;
        this.checkIn = checkIn;
        this.checkOut = checkOut;
    }

    public Integer getIdx() {
        return this.idx;
    }

    public Sign setIdx(Integer idx) {
        this.idx = idx;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Sign setName(String name) {
        this.name = name;
        return this;
    }

    public Integer getConfId() {
        return this.confId;
    }

    public Sign setConfId(Integer confId) {
        this.confId = confId;
        return this;
    }

    public String getDepart() {
        return this.depart;
    }

    public Sign setDepart(String depart) {
        this.depart = depart;
        return this;
    }

    public String getDeviceId() {
        return this.deviceId;
    }

    public Sign setDeviceId(String deviceId) {
        this.deviceId = deviceId;
        return this;
    }

    public String getCardId() {
        return this.cardId;
    }

    public Sign setCardId(String cardId) {
        this.cardId = cardId;
        return this;
    }

    public String getCardType() {
        return this.cardType;
    }

    public Sign setCardType(String cardType) {
        this.cardType = cardType;
        return this;
    }

    public LocalDateTime getCheckIn() {
        return this.checkIn;
    }

    public Sign setCheckIn(LocalDateTime checkIn) {
        this.checkIn = checkIn;
        return this;
    }

    public LocalDateTime getCheckOut() {
        return this.checkOut;
    }

    public Sign setCheckOut(LocalDateTime checkOut) {
        this.checkOut = checkOut;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sign (");

        sb.append(idx);
        sb.append(", ").append(name);
        sb.append(", ").append(confId);
        sb.append(", ").append(depart);
        sb.append(", ").append(deviceId);
        sb.append(", ").append(cardId);
        sb.append(", ").append(cardType);
        sb.append(", ").append(checkIn);
        sb.append(", ").append(checkOut);

        sb.append(")");
        return sb.toString();
    }
}
